language: php
php:
- 7
install:
- composer self-update
- composer install --dev --no-interaction --ignore-platform-reqs
script:
- phpunit --testsuite unit --tap --coverage-clover build/logs/clover.xml
- bash bin/codeclimate.sh
after_success:
- bash bin/deploy.sh
