language: php

php:
  - 7

install:
  - composer self-update
  - composer install --dev --no-interaction --ignore-platform-reqs

script:
  - phpunit --tap --coverage-clover build/logs/clover.xml

after_script:
  - bash bin/codeclimate.sh
